version: '3.9'

# Based on: https://www.ory.sh/run-oauth2-server-open-source-api-security/

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - ory

  hydra_migrate:
    init: true
    depends_on:
      - postgres
    image: oryd/hydra:v1.10.2
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
    command:
      - migrate
      - sql
      - --yes
      - --read-from-env
    networks:
      - ory

networks:
  ory:
